### PR TITLE
Only initialize Rhino engine if necessary

### PR DESCRIPTION
**Pull request by sdoeringNew**
The regex helper class has been refactored. The JavaScript functionality has been moved into two new (private) classes. One class for Nashorn, one for Rhino - both implementing the same interface for the regex checks. That enabled the strategy pattern and a cleaner separation of both JS engines.

And all by the way that refactoring solved the issue.

Additionally more test coverage has been added to the class as the Rhino engine has not been unit-tested before in case the build has been done with Java 8 - 14.

The formatting of the changed classes has been done by hand to match the odd code style.

### CODE REVIEW

**Comment by sdoeringNew** [comment]
There is also the RhinoHelper class, which is fully deprecated since three years now. That class only delegates to the Regex class. Shall I delete this RhinoHelper class?

**Comment by sdoeringNew** [comment]
I've tested this snapshot with an application. If I exclude Rhino from the build the application still starts because only Nashorn is (and needs to be) initialized. And additionally the Regex validation still gives me an error on invalid regular expression matches.

**Review by huggsboson — APPROVED** [review]
lgtm

**Comment by huggsboson** [comment]
I'd leave RhinoHelper for now since this project is largely in maintenance and no need to make upgrades harder on folks without good reason.

**Comment by huggsboson** [comment]
I'm gonna work on getting github build and publish action in place to release the new version.

**Pull request merged**
